import type { ExternalLearningResource } from './externalLearningTypes';

export const externalLearningResources: ExternalLearningResource[] = [
  {
    id: 'ms-learn-home',
    title: 'Microsoft Learn training homepage',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/',
    costLabel: 'free',
    level: 'beginner',
    format: 'module',
    estimatedTime: 'Self-paced',
    skillAreas: ['Microsoft 365', 'Entra ID', 'Intune', 'security', 'admin fundamentals'],
    relatedKbKeywords: ['m365', 'entra', 'intune', 'security', 'identity', 'admin'],
    bestUse: 'Use when a KB relates to Microsoft admin, M365, Entra, Intune, Exchange, security, or identity.',
    whyItHelps: 'Microsoft Learn provides guided modules and learning paths for cloud administration and modern service desk scenarios.'
  },
  {
    id: 'ms-learn-m365',
    title: 'Microsoft Learn browse M365 training',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/browse/?products=m365',
    costLabel: 'free',
    level: 'beginner',
    format: 'module',
    estimatedTime: 'Self-paced',
    skillAreas: ['Microsoft 365', 'Outlook', 'Exchange', 'admin fundamentals'],
    relatedKbKeywords: ['m365', 'outlook', 'exchange', 'teams', 'admin'],
    bestUse: 'Use for M365, Outlook, Exchange, Teams, or productivity tenant administration topics.',
    whyItHelps: 'A quick entry point for admins who want free, official Microsoft content and step-by-step training.'
  },
  {
    id: 'google-workspace-learning',
    title: 'Google Workspace Learning Center',
    provider: 'Google Workspace',
    url: 'https://support.google.com/a/users/',
    costLabel: 'free',
    level: 'beginner',
    format: 'documentation',
    estimatedTime: 'Quick reference',
    skillAreas: ['Google Workspace', 'Gmail', 'Google Drive', 'Google Meet', 'user support'],
    relatedKbKeywords: ['google', 'workspace', 'gmail', 'drive', 'meet', 'user support'],
    bestUse: 'Use when a KB card covers Google Workspace apps, user support, or email and collaboration issues.',
    whyItHelps: 'Official Google docs and training help support people with Workspace troubleshooting and end user guidance.'
  },
  {
    id: 'google-meet-help',
    title: 'Google Meet training and help',
    provider: 'Google Workspace',
    url: 'https://support.google.com/a/users/answer/9282720?hl=en',
    costLabel: 'free',
    level: 'beginner',
    format: 'documentation',
    estimatedTime: 'Quick read',
    skillAreas: ['Google Meet', 'user support', 'troubleshooting', 'meetings'],
    relatedKbKeywords: ['meet', 'video conferencing', 'meetings', 'support'],
    bestUse: 'Use for video conferencing issues, meeting setup, and Google Meet troubleshooting.',
    whyItHelps: 'This official guide helps agents solve common Meet problems with current product guidance.'
  },
  {
    id: 'cisco-networking-basics',
    title: 'Cisco Networking Basics',
    provider: 'Cisco Networking Academy',
    url: 'https://www.netacad.com/courses/networking-basics',
    costLabel: 'free',
    level: 'beginner',
    format: 'course',
    estimatedTime: '10-20 hours',
    skillAreas: ['networking', 'troubleshooting', 'DNS', 'Wi-Fi', 'internet issues'],
    relatedKbKeywords: ['network', 'dns', 'wifi', 'routing', 'connectivity', 'internet'],
    bestUse: 'Use when a KB card covers network basics, DNS issues, or Wi-Fi troubleshooting.',
    whyItHelps: 'A foundational course for support professionals who need common networking concepts and troubleshooting language.',
    cautionNote: 'Availability and course naming can change; verify before relying on the link.'
  },
  {
    id: 'harvard-cs50',
    title: 'Harvard CS50',
    provider: 'Harvard CS50',
    url: 'https://pll.harvard.edu/course/cs50-introduction-computer-science',
    costLabel: 'free audit',
    level: 'beginner',
    format: 'course',
    estimatedTime: '10+ weeks',
    skillAreas: ['programming fundamentals', 'problem solving', 'SQL', 'web basics', 'security concepts'],
    relatedKbKeywords: ['programming', 'code', 'sql', 'web', 'security', 'computing'],
    bestUse: 'Use for general computer science foundations and problem solving in technical support roles.',
    whyItHelps: 'CS50 teaches core logic, debugging, and algorithm thinking that helps with troubleshooting and automation.'
  },
  {
    id: 'mit-ocw',
    title: 'MIT OpenCourseWare',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/',
    costLabel: 'free',
    level: 'intermediate',
    format: 'curated library',
    estimatedTime: 'Self-paced',
    skillAreas: ['computer science', 'systems thinking', 'maths', 'engineering foundations'],
    relatedKbKeywords: ['systems', 'architecture', 'engineering', 'math', 'theory', 'computing'],
    bestUse: 'Use when a KB topic needs broader engineering or systems-level context beyond immediate troubleshooting.',
    whyItHelps: 'OCW offers free lecture notes and course materials for deeper technical understanding.'
  },
  {
    id: 'freecodecamp-learn',
    title: 'freeCodeCamp Learn',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/',
    costLabel: 'free',
    level: 'beginner',
    format: 'course',
    estimatedTime: 'Self-paced',
    skillAreas: ['web development', 'JavaScript', 'APIs', 'security', 'databases'],
    relatedKbKeywords: ['javascript', 'web', 'api', 'html', 'css', 'database'],
    bestUse: 'Use for web, automation, scripting, or tooling topics that benefit from coding fundamentals.',
    whyItHelps: 'freeCodeCamp has practical, hands-on lessons for developers and tech-support professionals.'
  },
  {
    id: 'codecademy-catalog',
    title: 'Codecademy catalog',
    provider: 'Codecademy',
    url: 'https://www.codecademy.com/catalog',
    costLabel: 'free with paid certificate option',
    level: 'beginner',
    format: 'course',
    estimatedTime: 'Self-paced',
    skillAreas: ['Python', 'HTML', 'CSS', 'JavaScript', 'SQL', 'cybersecurity', 'code foundations'],
    relatedKbKeywords: ['python', 'html', 'css', 'javascript', 'sql', 'cybersecurity'],
    bestUse: 'Use for beginner programming or automation skills when a KB topic goes beyond surface troubleshooting.',
    whyItHelps: 'Codecademy offers beginner-friendly paths and interactive coding practice for support tech skills.'
  },
  {
    id: 'w3schools',
    title: 'W3Schools',
    provider: 'W3Schools',
    url: 'https://www.w3schools.com/',
    costLabel: 'reference',
    level: 'beginner',
    format: 'reference',
    estimatedTime: 'Quick lookup',
    skillAreas: ['HTML', 'CSS', 'JavaScript', 'SQL', 'quick reference'],
    relatedKbKeywords: ['html', 'css', 'javascript', 'sql', 'reference'],
    bestUse: 'Use as a fast reference for web, script, and markup details that support troubleshooting and documentation.',
    whyItHelps: 'W3Schools is a lightweight reference for common syntax and examples when writing or reviewing code.'
  },
  {
    id: 'odin-project-foundations',
    title: 'The Odin Project Foundations',
    provider: 'The Odin Project',
    url: 'https://www.theodinproject.com/paths',
    costLabel: 'free',
    level: 'beginner',
    format: 'project path',
    estimatedTime: 'Self-paced',
    skillAreas: ['web development', 'Git', 'HTML', 'CSS', 'JavaScript', 'project-based learning'],
    relatedKbKeywords: ['project', 'git', 'html', 'css', 'javascript', 'development'],
    bestUse: 'Use when skill-building needs a structured, hands-on web development path.',
    whyItHelps: 'The Odin Project is ideal for learners who want project-based practice rather than only theory.'
  },
  {
    id: 'openlearn',
    title: 'OpenLearn',
    provider: 'OpenLearn',
    url: 'https://www.open.edu/openlearn/',
    costLabel: 'free',
    level: 'beginner',
    format: 'curated library',
    estimatedTime: 'Self-paced',
    skillAreas: ['workplace skills', 'communication', 'digital skills'],
    relatedKbKeywords: ['communication', 'workplace', 'digital skills', 'customer service'],
    bestUse: 'Use for communication, workplace judgement, or customer-facing support skills.',
    whyItHelps: 'OpenLearn has many free short courses for soft skills and workplace learning.'
  },
  {
    id: 'open-culture',
    title: 'Open Culture',
    provider: 'Open Culture',
    url: 'https://www.openculture.com/',
    costLabel: 'free',
    level: 'beginner',
    format: 'curated library',
    estimatedTime: 'Self-paced',
    skillAreas: ['broad learning', 'humanities', 'free courses', 'audiobooks'],
    relatedKbKeywords: ['culture', 'learning', 'audio', 'education', 'courses'],
    bestUse: 'Use for broader learning and general development after a communication or workplace scenario lesson.',
    whyItHelps: 'Open Culture gathers free courses and media across many subjects without registration.'
  },
  {
    id: 'coursera-browse',
    title: 'Coursera browse courses',
    provider: 'Coursera',
    url: 'https://www.coursera.org/courses',
    costLabel: 'free audit',
    level: 'intermediate',
    format: 'course',
    estimatedTime: 'Self-paced',
    skillAreas: ['professional development', 'technology', 'business', 'security'],
    relatedKbKeywords: ['course', 'audit', 'certificate', 'professional development'],
    bestUse: 'Use when learners want an extended course with audit options and certificate choice.',
    whyItHelps: 'Coursera is a broad hub for university-level courses with free audit pathways available in many areas.',
    cautionNote: 'Audit availability may change; verify free access before enrolling.'
  },
  {
    id: 'edx-learn',
    title: 'edX courses',
    provider: 'edX',
    url: 'https://www.edx.org/learn',
    costLabel: 'free audit',
    level: 'intermediate',
    format: 'course',
    estimatedTime: 'Self-paced',
    skillAreas: ['technology', 'management', 'data', 'security', 'engineering'],
    relatedKbKeywords: ['edx', 'audit', 'certificate', 'professional development'],
    bestUse: 'Use for free audit access to reputable university-level courses in tech and business topics.',
    whyItHelps: 'edX offers open course browsing and audit options from major institutions.',
    cautionNote: 'Audit/free availability may change; verify access before starting.'
  }
];
